### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by AnimMaDeR** [mrchrisster/mister_plex#1]
Connection was refused.  Not seeing anything obvious so I figure I'd post here.  Here is the log:

/media/fat/Scripts# mister_plex.sh
Please paste the full Plex URL (from 'Get XML' option):
http://localhost:32400/library/metadata/215619?checkFiles=1&includeAllConcerts=1                                                  &includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&inclu                                                  deExtras=1&includeFields=1&includeGeolocation=1&includeLoudnessRamps=1&includeMa                                                  rkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelat                                                  ed=1&includeRelatedCount=1&includeReviews=1&includeStations=1&X-Plex-Token=GkXXV                                                  poDSVury1ssfuYa
Updating video_mode in MiSTer.ini...
Checking and modifying /media/fat/MiSTer.ini for samvideo playback.
Missing or incorrect value for video_mode in [menu].
MiSTer.ini modified successfully.
MiSTer.ini updated successfully with video_mode:
Generated Transcode URL:
http://localhost:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Ch                                                  rome&copyts=1&mediaIndex=0&offset=0&path=%2Flibrary%2Fmetadata%2F215619&videoRes                                                  olution=320x240&maxVideoBitrate=1000&X-Plex-Token=GkXXVpoDSVury1ssfuYa&directStr                                                  eam=0&directPlay=0
Preparing mplayer
Ctrl +c to cancel playback
/media/fat/Scripts/.MiSTer_SAM/mplayer: /lib/libasound.so.2: no version informat                                                  ion available (required by /media/fat/Scripts/.MiSTer_SAM/mplayer)
/media/fat/Scripts/.MiSTer_SAM/mplayer: /lib/libasound.so.2: no version informat                                                  ion available (required by /media/fat/Scripts/.MiSTer_SAM/mplayer)
/media/fat/Scripts/.MiSTer_SAM/mplayer: /lib/libasound.so.2: no version informat                                                  ion available (required by /media/fat/Scripts/.MiSTer_SAM/mplayer)
Creating config file: /root/.mplayer/config
MPlayer 1.5-10 (C) 2000-2022 MPlayer Team

Playing http://localhost:32400/video/:/transcode/universal/start.m3u8?X-Plex-Pla                                                  tform=Chrome&copyts=1&mediaIndex=0&offset=0&path=%2Flibrary%2Fmetadata%2F215619&                                                  videoResolution=320x240&maxVideoBitrate=1000&X-Plex-Token=GkXXVpoDSVury1ssfuYa&d                                                  irectStream=0&directPlay=0.
Resolving localhost for AF_INET...
Connecting to server localhost[127.0.0.1]: 32400...

connect error: Connection refused
STREAM_ASF, URL: http://localhost:32400/video/:/transcode/universal/start.m3u8?X                                                  -Plex-Platform=Chrome&copyts=1&mediaIndex=0&offset=0&path=%2Flibrary%2Fmetadata%                                                  2F215619&videoResolution=320x240&maxVideoBitrate=1000&X-Plex-Token=GkXXVpoDSVury                                                  1ssfuYa&directStream=0&directPlay=0
Resolving localhost for AF_INET...
Connecting to server localhost[127.0.0.1]: 32400...

connect error: Connection refused
Failed, exiting.
libavformat version 59.17.102 (internal)
[tcp @ 0x1333034]Connection to tcp://localhost:32400 failed: Error number -111 o                                                  ccurred
Failed to open http://localhost:32400/video/:/transcode/universal/start.m3u8?X-P                                                  lex-Platform=Chrome&copyts=1&mediaIndex=0&offset=0&path=%2Flibrary%2Fmetadata%2F                                                  215619&videoResolution=320x240&maxVideoBitrate=1000&X-Plex-Token=GkXXVpoDSVury1s                                                  sfuYa&directStream=0&directPlay=0.

Exiting... (End of file)

**Comment by AnimMaDeR** [comment]
I can also verify that secure connections are set to preferred in Plex network settings.  I am running Plex server on a Mini PC that pulls media from a Synology NAS.

**Comment by mrchrisster** [comment]
Ah interesting. So you see where it says localhost in the URL? That's probably why it's not working. My Plex server is remote so when I click on view XML it generates a link with a Plex IP. Try replacing localhost with the up where your Plex server is. I'll send you another command to try out so we find out how to call the right IP through Plex API

**Comment by AnimMaDeR** [comment]
That did it!  

I was snagging the link from the mini PC web browser which must have been why it gave me localhost.  When I snagged the link from my laptop, that worked.  However, my content plays funny.  Jaws (720x362) played in the upper left corner at a tall-stretch aspect ratio, and the Mouse and his Child (VHS rip at 640x480) plays only on the left side of the screen but fills top to bottom (just super squished horizontally).  Have you noticed that in your testing?  

Thanks so much for the help!  This is a big deal addition to MiSTer!  I would love to help contribute if I can. Eager to get Live TV playing from Plex to MiSTer.

**Comment by mrchrisster** [comment]
Every display is different so it's hard to find a solution for every display. It sounds like you are using a HDMI device... maybe try sv_aspectfix in mister-plex-hdmi.sh to yes

**Comment by AnimMaDeR** [comment]
I am using a CRT and not an HDMI device but do at least see a centered image on my CRT when using the hdmi script. However the image is still squished horizontally by a factor of 2.  

I am going to close this issue since the connection works and start a new issue on scaling and positioning.  Thank you.

**Comment by mrchrisster** [comment]
ok i added the centering to the crt script. did you modify the crt `video_mode` ?
you can also try the alt setting: https://github.com/mrchrisster/mister_plex/blob/f05720e024da5a7d826818636cde6dc93f36800f/mister_plex.sh#L19
